name: Label Issues (Script Injection Example)
on:
  issues:
    types:
      - opened
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        #hrozi injection bug, pretoze title sa spracovava v shelle
        # run: |
        #   issue_title="${{ github.event.issue.title }}"
        #   if [[ "$issue_title" == *"bug"* ]]; then
        #   echo "Issue is about a bug!"
        #   else
        #   echo "Issue is not about a bug"
        #   fi

        #lepsie takto...cez env. variable nehrozi injection!
        env:
          TITLE: '${{ github.event.issue.title }}'
        run: |
          if [[ "$TITLE" == *"bug"* ]]; then
          echo "Issue is about a bug!"
          else
          echo "Issue is not about a bug"
          fi
